inputs:
  name: 
    description: 'Name of the parent Job'
    default: 'No name provided'
runs:
  using: "composite"
  steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Create local.properties 
        shell: bash
        run: |
          touch ./local.properties
          echo "âš™ï¸ Creating a new local.properties file"
          echo "sdk.dir=ANDROID_SDK_ROOT" > ./local.properties
          
      - name: ğŸ§¹ Check Lint
        run: ./gradlew app:lint
      
      - name: ğŸ§ª Run tests
        run: ./gradlew app:test

      - name: ğŸ“¦ Build the app
        run: ./gradlew app:assembleDebug