runs:
	using: "composite"
	steps:
		- name: ğŸ Releasing using Hub
		uses: ShaunLWM/action-release-debugapk@master
		env:
		  GITHUB_TOKEN: ${{ secrets.TOKEN }}
		  APP_FOLDER: app
		  RELEASE_TITLE: Meraki App Release